[server.grpc]
addr = ":50051"

[server.http]
addr = ":8081"

[log]
file = "logs/{{YYYY}}{{MM}}{{DD}}{{hh}}.log"
symlink = "logs/dauth.log"
level = "debug"
max_age = "168h"
max_backups = 0
output_type = "both"

[db]
user = "root"
password = "u6xYzLEu4xZQg2jPJHMk"
database = "dauth"
addr = "infra.dauth.com:3306"

[registry]
addr = "infra.dauth.com:8500"

[tracing]
endpoint = "infra.dauth.com:4317"
endpoint_type = "grpc"
insecure = true
